# Generated by Django 5.1.3 on 2024-12-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="promotionbanner",
            name="edit_by",
        ),
    ]
