# Generated by Django 5.1.3 on 2024-11-18 22:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_options"),
        ("shop", "0002_alter_promotionbanner_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("customer", "product")},
        ),
    ]
