# Generated by Django 5.1.3 on 2024-12-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="category",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="color",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="size",
            name="edit_by",
        ),
    ]
