# Generated by Django 4.2 on 2024-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_options_alter_brand_edit_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_level",
            field=models.SmallIntegerField(
                choices=[(0, "Gender/Age"), (1, "Type_clothes")], default=0
            ),
            preserve_default=False,
        ),
    ]
