# Generated by Django 4.2 on 2024-11-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_category_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.color",
            ),
        ),
    ]
