# Generated by Django 4.2 on 2024-11-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                null=True, related_name="products", to="products.size"
            ),
        ),
    ]
