# Generated by Django 4.2 on 2024-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_size_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(related_name="products", to="products.size"),
        ),
    ]
