# Generated by Django 5.1.3 on 2024-11-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-create_date"]},
        ),
    ]
