# Generated by Django 5.1.3 on 2024-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/accounts/customer_photos"
            ),
        ),
    ]
