server{
    listen 80 default_server;
    listen 443 default_server;

    server_name modnyk;

    location /static/ {
        alias /modnyk/src/static/;
    }

    location /media/ {
            alias /modnyk/src/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://backend:8000;
    }
}