# Generated by Django 4.2 on 2024-11-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Self-pickup"),
                    (2, "Courier delivery"),
                    (3, "Shipping"),
                    (4, "Postal delivery"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Pending"),
                    (2, "Open"),
                    (3, "Shipping"),
                    (4, "Shipped"),
                    (5, "Delivered"),
                    (6, "Canceled"),
                    (7, "Returned"),
                ],
                null=True,
            ),
        ),
    ]
