# Generated by Django 4.2 on 2024-11-09 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_alter_order_shipping_type_alter_order_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippingAddress",
            new_name="DeliveryAddress",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address",
            new_name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_type",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Self-pickup"),
                    (1, "Courier delivery"),
                    (2, "Shipping"),
                    (3, "Postal delivery"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Pending"),
                    (1, "Open"),
                    (2, "Shipping"),
                    (3, "Shipped"),
                    (4, "Delivered"),
                    (5, "Canceled"),
                    (6, "Returned"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.SmallIntegerField(
                blank=True, choices=[(0, "By cash"), (1, "By card")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "Pending"), (1, "Cancelled"), (2, "Payed")],
                null=True,
            ),
        ),
    ]
