# Generated by Django 5.1.3 on 2024-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_deliveryaddress_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="cost_of_delivery",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
