# Generated by Django 5.1.3 on 2024-11-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_deliveryaddress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ManyToManyField(
                null=True, related_name="order_payments", to="orders.order"
            ),
        ),
    ]
