# Generated by Django 5.1.3 on 2024-11-18 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_payment_order_payment_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_payments",
                to="orders.order",
            ),
        ),
    ]
