# Generated by Django 5.1.3 on 2024-12-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="edit_by",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="edit_by",
        ),
    ]
