# Generated by Django 4.2 on 2024-11-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_size"),
        ("cart", "0002_alter_cart_edit_by_alter_cartitem_edit_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.size",
            ),
            preserve_default=False,
        ),
    ]
